### ISSUE TITLE
Create Marketplace

### ISSUE THREAD

**Issue by rajpatel486** [TonyKimisintheHouse/Raj-s-Jar-Files#44]
1. From your game screen have a way to get to the market (located on the planet the player is currently on.  Since we cannot travel yet, that would be the planet the player starts on).
2. In the market, display the trade goods that are for sale and the trade goods currently on the ship
3. Be able to sell trade goods on the ship
4. Be able to buy trade goods from the market. They should then go into the cargo hold
5. You cannot buy more goods than you have money or cargo space.
6. You cannot sell more goods than are in your cargo space.
7. Prices are determined through some model and not fixed
8. Quantity produced varies by planet

**Comment by soohl** [comment]
- [x] 1. From your game screen have a way to get to the market (located on the planet the player is currently on.  Since we cannot travel yet, that would be the planet the player starts on).
- [x] 2. In the market, display the trade goods that are for sale and the trade goods currently on the ship
- [x] 3. Be able to sell trade goods on the ship
- [x] 4. Be able to buy trade goods from the market. They should then go into the cargo hold
- [x] 5. You cannot buy more goods than you have money or cargo space.
- [x] 6. You cannot sell more goods than are in your cargo space.
- [x] 7. Prices are determined through some model and not fixed
- [x] 8.  Quantity produced varies by planet

**TODO:**
1. Market UI
2. Connect market with the ship cargo
3. JavaDocs
4. Unit Tester

**The trading system is a real mess. We should ultimately employ transaction class with validation method**
